import { ThemeProvider } from '@/lib/ThemeContext';
import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';

const inter = Manrope({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ThemeProvider>
  )
}
