import { ThemeProvider } from '@/lib/ThemeContext';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import ReactQueryProvider from '@/lib/ReactQueryProvider';
import { Sidebar } from 'lucide-react';
import SideBar from '@/components/reuseble/sidebar';
import SessionProviderComp from '@/lib/sessionProvider';
import SidebarProviderComp from '@/lib/sidebarProvider';
import Left from '@/components/app/feed/left';

const inter = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: '400'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ThemeProvider>
      <html lang="en" className="dark" style={{ colorScheme: 'dark' }}>
        <body className={`${inter.className} bg-black`}>
          <SidebarProviderComp>
            <SessionProviderComp>
              <ReactQueryProvider>
                <div className=' md:flex md:flex-row md:flex-shrink bg-black md:flex-1 max-h-screen mx-auto ' style={{ colorScheme: 'dark' }}>
                  <SideBar />
                  <div className='md:flex-1 md:flex-grow md:mx-auto bg-black ' style={{ colorScheme: 'dark' }}>
                    {children}
                  </div>

                  <div className=" md:hidden flex w-full fixed mx-auto bottom-0 justify-center items-center">
                    <Left />
                  </div>
                </div>
              </ReactQueryProvider>
            </SessionProviderComp>
          </SidebarProviderComp>
        </body>
      </html>
    </ThemeProvider>
  )
}
